services:
  server:
    image: "swiftlang/swift:nightly-focal"
    volumes:
      - /Users/yyoongs/code/labs/swift:/code
    environment:
      - USER=yyoongs
    command: bash -c "apt-get update && apt-get install nodejs && node /code/node/app.js"
  client:
    image: "swiftlang/swift:nightly-focal"
    volumes:
      - /Users/yyoongs/code/labs/swift:/code
    environment:
      - USER=yyoongs
